from os.path import abspath


def read_aws_configuration_file(aws_config_file: str = '~/.aws/credentials', profile_regex: str = None) -> dict:
    """
    Read the AWS configuration file and return the configuration as a dictionary.

    Args:
        aws_config_file (str): The path to the AWS configuration file.
        profile_regex (str, optional): A regular expression to filter the profiles. If not provided, all profiles are returned.
    """

    from os.path import abspath, expanduser
    from configparser import ConfigParser

    config = ConfigParser()
    config.read(abspath(expanduser(aws_config_file)))

    config_dict = {section: dict(config.items(section)) for section in config.sections()}

    if profile_regex:
        from re import compile
        regex = compile(profile_regex)
        result = {k: v for k, v in config_dict.items() if regex.match(k)}

    else:
        result = config_dict

    return result


def write_aws_configuration_file(aws_config: dict, aws_config_file: str = '~/.aws/credentials', preserve_other_credentials: bool = True):
    """
    Write the AWS configuration to the configuration file.

    Args:
        aws_config_file (str): The path to the AWS configuration file.
        aws_config (dict): The AWS configuration.
        preserve_other_credentials (bool, optional): If False, only credentials generated by Harvest are preserved. Default is True.
    """

    if preserve_other_credentials:
        output_config = aws_config

    else:
        output_config = {k: v for k, v in aws_config.items() if k.startswith('harvest_') or k == 'default'}

    from os.path import abspath, expanduser
    from configparser import ConfigParser
    config = ConfigParser()
    config.read_dict(output_config)

    with open(abspath(expanduser(aws_config_file)), 'w') as file:
        config.write(file)
