report:
  name: reports.aws.rds.parameters
  description: Retrieve information about RDS Cluster and Instance parameters.

  headers:
    - Active
    - Account
    - Region
    - Type
    - Group
    - Family
    - Parameter
    - Value
    - Source
    - ApplyMethod

  tasks:
    - mongo: &cluster
        name: Cluster Parameter Groups
        silo: harvest-core
        collection: aws.rds.parameters-cluster
        filters: '.*'
        result_as: cluster_parameter_groups
        arguments:
          pipeline:
            - $unwind:  &unwind
                path: "$Parameters"
                preserveNullAndEmptyArrays: true

            - $project: &projection
                Active: "$Harvest.Active"
                Account: "$Harvest.Account"
                Region: "$Harvest.Region"
                Type: "cluster"
                Group: "$DBClusterParameterGroupName"
                Family: "$DBParameterGroupFamily"
                Parameter: "$Parameters.ParameterName"
                Value: "$Parameters.ParameterValue"
                Source: "$Parameters.Source"
                ApplyMethod: "$Parameters.ApplyMethod"

    - mongo:
        <<: *cluster
        name: Instance Parameter Groups
        collection: aws.rds.parameters-instance
        result_as: instance_parameter_groups
        arguments:
          pipeline:
            - $unwind:
                <<: *unwind

            - $project:
                <<: *projection
                Type: "instance"
                Group: "$DBParameterGroupName"

    - dataset:
        name: Combine Parameter Groups
        filters: 'limit'
        stages:
          - add_records:
              records: var.cluster_parameter_groups
          - add_records:
              records: var.instance_parameter_groups
